/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginImport } from './routes/login'
import { Route as IndexImport } from './routes/index'
import { Route as GroupGroupIdImport } from './routes/group/$groupId'
import { Route as GroupGroupIdExerciseExerciseIdImport } from './routes/group_/$groupId.exercise.$exerciseId'

// Create/Update Routes

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const GroupGroupIdRoute = GroupGroupIdImport.update({
  id: '/group/$groupId',
  path: '/group/$groupId',
  getParentRoute: () => rootRoute,
} as any)

const GroupGroupIdExerciseExerciseIdRoute =
  GroupGroupIdExerciseExerciseIdImport.update({
    id: '/group_/$groupId/exercise/$exerciseId',
    path: '/group/$groupId/exercise/$exerciseId',
    getParentRoute: () => rootRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/group/$groupId': {
      id: '/group/$groupId'
      path: '/group/$groupId'
      fullPath: '/group/$groupId'
      preLoaderRoute: typeof GroupGroupIdImport
      parentRoute: typeof rootRoute
    }
    '/group_/$groupId/exercise/$exerciseId': {
      id: '/group_/$groupId/exercise/$exerciseId'
      path: '/group/$groupId/exercise/$exerciseId'
      fullPath: '/group/$groupId/exercise/$exerciseId'
      preLoaderRoute: typeof GroupGroupIdExerciseExerciseIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/group/$groupId': typeof GroupGroupIdRoute
  '/group/$groupId/exercise/$exerciseId': typeof GroupGroupIdExerciseExerciseIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/group/$groupId': typeof GroupGroupIdRoute
  '/group/$groupId/exercise/$exerciseId': typeof GroupGroupIdExerciseExerciseIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/group/$groupId': typeof GroupGroupIdRoute
  '/group_/$groupId/exercise/$exerciseId': typeof GroupGroupIdExerciseExerciseIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/group/$groupId'
    | '/group/$groupId/exercise/$exerciseId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/group/$groupId'
    | '/group/$groupId/exercise/$exerciseId'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/group/$groupId'
    | '/group_/$groupId/exercise/$exerciseId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  GroupGroupIdRoute: typeof GroupGroupIdRoute
  GroupGroupIdExerciseExerciseIdRoute: typeof GroupGroupIdExerciseExerciseIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  GroupGroupIdRoute: GroupGroupIdRoute,
  GroupGroupIdExerciseExerciseIdRoute: GroupGroupIdExerciseExerciseIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/login",
        "/group/$groupId",
        "/group_/$groupId/exercise/$exerciseId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/group/$groupId": {
      "filePath": "group/$groupId.tsx"
    },
    "/group_/$groupId/exercise/$exerciseId": {
      "filePath": "group_/$groupId.exercise.$exerciseId.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
